### ISSUE TITLE
NoBrokersAvailable

### ISSUE THREAD

**Issue by wbarnha** [wbarnha/kafka-python-ng#65]
While trying to run the producer I keep on getting this issue, I have tried adding api_version to the code but its not working. Can anybody help

Traceback (most recent call last):
  File "C:/Users/Aditya Anand/Nudity_detection-on-Live-Video-Stream/consumer.py", line 12, in <module>
    consumer = KafkaConsumer(
  File "C:\Users\Aditya Anand\AppData\Local\Programs\Python\Python38\lib\site-packages\kafka\consumer\group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "C:\Users\Aditya Anand\AppData\Local\Programs\Python\Python38\lib\site-packages\kafka\client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "C:\Users\Aditya Anand\AppData\Local\Programs\Python\Python38\lib\site-packages\kafka\client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

Process finished with exit code 1

**Comment by truonglac2603** [comment]
Facing the same issue. I'm using 3 domains for KAFKA_BROKER, don't know if this is the problem or not
